apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-cpu-alert
  namespace: monitoring

spec:
  groups:
  - name: cpu-alerts

    rules:
    - alert: HighCPUUsage

      expr: (
              sum(rate(container_cpu_usage_seconds_total[5m])) by (pod)
              * 100
            ) > 80

      for: 5m

      labels:
        severity: warning

      annotations:
        summary: "High CPU Usage"

        description: "Pod CPU usage exceeded 80% for more than 5 minutes."
