apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pvc-storage-high-alert
  namespace: monitoring

spec:
  groups:
  - name: pvc-alerts

    rules:
    - alert: PVCStorageHigh

      expr: (
              kubelet_volume_stats_used_bytes
              /
              kubelet_volume_stats_capacity_bytes
            ) * 100 > 80

      for: 5m

      labels:
        severity: warning

      annotations:
        summary: "PVC utilization above 80%"

        description: "Persistent Volume usage exceeded 80% for more than 5 minutes."
