---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: can-parser
  namespace: monitoring
  labels:
    release: prometheus

spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: parser
      app.kubernetes.io/name: parser
      
  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: metrics
      interval: 15s
